### ISSUE TITLE
Missing build assets for release 1.6.3

### ISSUE THREAD

**Issue by philclifford** [mapitman/mdview#37]
The release action seems to have failed to upload most of the build assets yet thinks this is a success.

**Comment by mapitman** [comment]
I deleted the release. It didn't go as planned anyway. I assume this was breaking something with deb-get. Will that fix the problem for now?

**Comment by philclifford** [comment]
Yes it's fine now thanks: deb-get was looking for debs on the "Latest" tagged release and being upset, but the breakage was limited to outputting errors and failing to let users install `mdview`.  It's easy enough to get all the released assets from the api and take the latest .deb, which works but is not as "accurate" as a general rule. It's trivial for deb-get users to work around it, but you've fixed it for them so thanks for that.
I hope a more satisfactory release doesn't prove too onerous.
