### ISSUE TITLE
Permission denied when accessing file on mounted SDCard

### ISSUE THREAD

**Issue by dualhammers** [mapitman/mdview#9]
![image](https://user-images.githubusercontent.com/7495830/95553588-15e15780-09cc-11eb-8623-af726ac12ed0.png)

**Comment by mapitman** [comment]
What platform are you running on? How did you install?

**Comment by dualhammers** [comment]
Running Manjaro Mikah 20.1.1

Installed via the Snap.

[image: image.png]

**Comment by mapitman** [comment]
OK, that's a problem with Snap packages. Unless they ask for the `removable-media` interface, they are unable to access things like SD cards. I hadn't considered adding that interface to the Snap package. I can do that, but it still won't autoconnect. You'd have to run this command:
```sh
snap connect mdview:removable-media :removable-media
```

**Comment by mapitman** [comment]
An alternative would be to uninstall the Snap package and download the [latest binary](https://github.com/mapitman/mdview/releases/download/1.4.0/mdview-1.4.0-linux-amd64.tar.gz). Then just untar and copy the binary to a directory in your path.

If you happen to have Golang installed, you can also run: 
```sh
go get github.com/mapitman/mdview
```

I've also thought about building native packages for various platforms, but haven't gotten around to it yet.

**Comment by dualhammers** [comment]
OK, Thanks! I will figure it out.

**Comment by mapitman** [comment]
I built a .deb package last night. I'm going to look into what it takes to get something into the AUR and try making a package for Arch and Arch-based distros soon.

**Comment by mapitman** [comment]
I just pushed a PKGBUILD to the AUR here: https://aur.archlinux.org/packages/mdview/

I'd suggest using that on an Arch-based distro such as Manjaro.
